<?php

/**
 * Argentina Places
 *
 * @author   Marketing Rapel
 * @version  1.1.26
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['AR'] = array(
	'AR_B' => array(
        'Ciudad Autónoma de Buenos Aires',
		'Adolfo Alsina',
		'Adolfo Gonzales Chaves',
		'Alberti',
		'Almirante Brown',
		'Arrecifes',
		'Avellaneda',
		'Ayacucho',
		'Azul',
		'Bahía Blanca',
		'Balcarce',
		'Baradero',
		'Benito Juárez',
		'Berazategui',
		'Berisso',
		'Bolívar',
		'Bragado',
		'Brandsen',
		'Campana',
		'Cañuelas',
		'Capitán Sarmiento Carlos',
		'Carlos Casares',
		'Carlos Tejedor',
		'Carmen de Areco',
		'Castelli',
		'Chacabuco',
		'Chascomús',
		'Chivilcoy',
		'Colón',
		'Coronel de Marina Leonardo Rosales',
		'Coronel Dorrego',
		'Coronel Pringles',
		'Coronel Suárez',
		'Daireaux',
		'Dolores',
		'Ensenada',
		'Escobar',
		'Esteban Echeverría',
		'Exaltación de la Cruz',
		'Ezeiza',
		'Florencio Varela',
		'Florentino Ameghino',
		'General Alvarado',
		'General Alvear',
		'General Arenales',
		'General Belgrano',
		'General Guido',
		'General Juan Madariaga',
		'General La Madrid',
		'General Las Heras',
		'General Lavalle',
		'General Paz',
		'General Pinto',
		'General Pueyrredón',
		'General Rodríguez',
		'General San Martín',
		'General Viamonte',
		'General Villegas',
		'Guaminí',
		'Hipólito Yrigoyen',
		'Hurlingham',
		'Ituzaingó',
		'José C. Paz',
		'Junín',
		'La Costa',
		'La Matanza',
		'Lanús',
		'La Plata',
		'Laprida',
		'Las Flores',
		'Leandro N. Alem',
		'Lincoln',
		'Lobería',
		'Lobos',
		'Lomas de Zamora',
		'Luján',
		'Magdalena',
		'Maipú',
		'Malvinas Argentinas',
		'Mar Chiquita',
		'Marcos Paz',
		'Mercedes',
		'Merlo',
		'Monte',
		'Monte Hermoso',
		'Moreno',
		'Morón',
		'Navarro',
		'Necochea',
		'Nueve de Julio (9 de Julio)',
		'Olavarría',
		'Patagones',
		'Pehuajó',
		'Pellegrini',
		'Pergamino',
		'Pila',
		'Pilar',
		'Pinamar',
		'Presidente Perón',
		'Puan',
		'Punta Indio',
		'Quilmes',
		'Ramallo',
		'Rauch',
		'Rivadavia',
		'Rojas',
		'Roque Pérez',
		'Saavedra',
		'Saladillo',
		'Salliqueló',
		'Salto',
		'San Andrés de Giles',
		'San Antonio de Areco',
		'San Cayetano',
		'San Fernando',
		'San Isidro',
		'San Miguel',
		'San Nicolás',
		'San Pedro',
		'San Vicente',
		'Suipacha',
		'Tandil',
		'Tapalqué',
		'Tigre',
		'Tordillo',
		'Tornquist',
		'Trenque Lauquen',
		'Tres Arroyos',
		'Tres de Febrero',
		'Tres Lomas',
		'Veinticinco de Mayo (25 de Mayo)',
		'Vicente López',
		'Villa Gesell',
		'Villarino',
		'Zárate'
	),
	'AR_K' => array(
		'Ambato',
		'Ancasti',
		'Andalgalá',
		'Antofagasta de la Sierra',
		'Belén',
		'Capayán',
		'Catamarca',
		'El Alto',
		'Fray Mamerto Esquiú',
		'La Paz',
		'Paclín',
		'Pomán',
		'Santa María',
		'Santa Rosa',
		'Tinogasta',
		'Valle Viejo'
	),
	'AR_H' => array(
		'Almirante Brown',
		'Bermejo',
		'Chacabuco',
		'Comandante Fernández',
		'Doce de Octubre (12 de Octubre)',
		'Dos de Abril (2 de Abril)',
		'Fray Justo Santa María de Oro',
		'General Belgrano',
		'General Donovan',
		'General Güemes',
		'Independencia',
		'Libertad',
		'Libertador General San Martín',
		'Maipú',
		'Mayor Luis Jorge Fontana',
		'Nueve de Julio (9 de Julio)',
		'O\'Higgins',
		'Presidencia de la Plaza',
		'Primero de Mayo (1º de Mayo)',
		'Quitilipi',
		'San Fernando',
		'San Lorenzo',
		'Sargento Cabral',
		'Tapenagá',
		'Veinticinco de Mayo (25 de Mayo)',
	),
	'AR_U' => array(
		'Biedma',
		'Cushamen',
		'Escalante',
		'Florentino Ameghino',
		'Futaleufú',
		'Gaiman',
		'Gastre',
		'Languiñeo',
		'Mártires',
		'Paso de Indios',
		'Rawson',
		'Río Senguer',
		'Sarmiento',
		'Tehuelches',
		'Telsen'
	),
	'AR_X' => array(
		'Calamuchita',
		'Córdoba',
		'Colón',
		'Cruz del Eje',
		'General Roca',
		'General San Martín',
		'Ischilín',
		'Juárez Celman',
		'Marcos Juárez',
		'Minas',
		'Pocho',
		'Presidente Roque Sáenz Peña',
		'Punilla',
		'Río Cuarto',
		'Río Primero',
		'Río Seco',
		'Río Segundo',
		'San Alberto',
		'San Javier',
		'San Justo',
		'Santa María',
		'Sobremonte',
		'Tercero Arriba',
		'Totoral',
		'Tulumba',
		'Unión'
	),
	'AR_W' => array(
		'Bella Vista',
		'Berón de Astrada',
		'Corrientes',
		'Concepción',
		'Curuzú Cuatiá',
		'Empedrado',
		'Esquina',
		'General Alvear',
		'General Paz',
		'Goya',
		'Itatí',
		'Ituzaingó',
		'Lavalle',
		'Mburucuyá',
		'Mercedes',
		'Monte Caseros',
		'Paso de los Libres',
		'Saladas',
		'San Cosme',
		'San Luis del Palmar',
		'San Martín',
		'San Miguel',
		'San Roque',
		'Santo Tomé',
		'Sauce'
	),
	'AR_E' => array(
		'Colón',
		'Concordia',
		'Diamante',
		'Federación',
		'Federal',
		'Feliciano',
		'Gualeguay',
		'Gualeguaychú',
		'Islas del Ibicuy',
		'La Paz',
		'Nogoyá',
		'Paraná',
		'San Salvador',
		'Tala',
		'Uruguay',
		'Victoria',
		'Villaguay'
	),
	'AR_P' => array(
		'Bermejo',
		'Formosa',
		'Laishi',
		'Matacos',
		'Patiño',
		'Pilagás',
		'Pilcomayo',
		'Pirané',
		'Ramón Lista'
	),
	'AR_Y' => array(
		'Cochinoca',
		'Doctor Manuel Belgrano',
		'El Carmen',
		'Humahuaca',
		'Ledesma',
		'Palpalá',
		'Rinconada',
		'San Antonio',
		'San Pedro',
		'Santa Bárbara',
		'Santa Catalina',
		'Susques',
		'Tilcara',
		'Tumbaya',
		'Valle Grande',
		'Yavi'
	),
	'AR_L' => array(
		'Atreucó',
		'Caleu Caleu',
		'Capital',
		'Catriló',
		'Chalileo',
		'Chapaleufú',
		'Chical Co',
		'Conhelo',
		'Curacó',
		'Guatraché',
		'Hucal',
		'Lihuel Calel',
		'Limay Mahuida',
		'Loventué',
		'Maracó',
		'Puelén',
		'Quemú Quemú',
		'Rancul',
		'Realicó',
		'Toay',
		'Trenel',
		'Utracán'
	),
	'AR_F' => array(
		'Arauco',
		'La Rioja',
		'Castro Barros',
		'Chamical',
		'Chilecito',
		'Coronel Felipe Varela',
		'Famatina',
		'General Ángel V. Peñaloza',
		'General Belgrano',
		'General Juan Facundo Quiroga',
		'General Lamadrid',
		'General Ocampo',
		'General San Martín',
		'Independencia',
		'Rosario Vera Peñaloza',
		'Sanagasta',
		'San Blas de los Sauces',
		'Vinchina'
	),
	'AR_M' => array(
		'Mendoza',
		'General Alvear',
		'Godoy Cruz',
		'Guaymallén',
		'Junín',
		'La Paz',
		'Las Heras',
		'Lavalle',
		'Luján de Cuyo',
		'Maipú',
		'Malargüe',
		'Rivadavia',
		'San Carlos',
		'San Martín',
		'San Rafael',
		'Santa Rosa',
		'Tunuyán',
		'Tupungato'
	),
	'AR_N' => array(
		'Apóstoles',
		'Cainguás',
		'Candelaria',
		'Misiones',
		'Concepción',
		'Eldorado',
		'General Manuel Belgrano',
		'Guaraní',
		'Iguazú',
		'Leandro N. Alem',
		'Libertador General San Martín',
		'Montecarlo',
		'Oberá',
		'San Ignacio',
		'San Javier',
		'San Pedro',
		'Veinticinco de Mayo (25 de Mayo)'
	),
	'AR_Q' => array(
		'Aluminé',
		'Añelo',
		'Catán Lil',
		'Chos Malal',
		'Collón Curá',
		'Confluencia',
		'Huiliches',
		'Lácar',
		'Loncopué',
		'Los Lagos',
		'Minas',
		'Ñorquín',
		'Pehuenches',
		'Picunches',
		'Picún Leufú',
		'Zapala'
	),
	'AR_R' => array(
		'Adolfo Alsina',
		'Avellaneda',
		'Bariloche',
		'Conesa',
		'El Cuy',
		'General Roca',
		'Ñorquincó',
		'Nueve de Julio (9 de Julio)',
		'Pichi Mahuida',
		'Pilcaniyeu',
		'San Antonio',
		'Valcheta',
		'Veinticinco de Mayo (25 de Mayo)'
	),
	'AR_A' => array(
		'Anta',
		'Cachi',
		'Cafayate',
		'Salta',
		'Cerrillos',
		'Chicoana',
		'General Güemes',
		'General José de San Martín',
		'Guachipas',
		'Iruya',
		'La Caldera',
		'La Candelaria',
		'La Poma',
		'La Viña',
		'Los Andes',
		'Metán',
		'Molinos',
		'Orán',
		'Rivadavia',
		'Rosario de la Frontera',
		'Rosario de Lerma',
		'San Carlos',
		'Santa Victoria'
	),
	'AR_J' => array(
		'Albardón',
		'Angaco',
		'Calingasta',
		'San Juan',
		'Caucete',
		'Chimbas',
		'Iglesia',
		'Jáchal',
		'Nueve de Julio (9 de Julio)',
		'Pocito',
		'Rawson',
		'Rivadavia',
		'San Martín',
		'Santa Lucía',
		'Sarmiento',
		'Ullum',
		'Valle Fértil',
		'Veinticinco de Mayo (25 de Mayo)',
		'Zonda'
	),
	'AR_D' => array(
		'Ayacucho',
		'Belgrano',
		'Chacabuco',
		'Coronel Pringles',
		'General Pedernera',
		'Gobernador Dupuy',
		'Junín',
		'La Capital (Juan Martín de Pueyrredón)',
		'Libertador General San Martín'
	),
	'AR_Z' => array(
		'Corpen Aike',
		'Deseado',
		'Güer Aike',
		'Lago Argentino',
		'Lago Buenos Aires',
		'Magallanes',
		'Río Chico'
	),
	'AR_S' => array(
		'Belgrano',
		'Caseros',
		'Castellanos',
		'Constitución',
		'Garay',
		'General López',
		'General Obligado',
		'Iriondo',
		'La Capital',
		'Las Colonias',
		'Nueve de Julio (9 de Julio)',
		'Rosario',
		'San Cristóbal',
		'San Javier',
		'San Jerónimo',
		'San Justo',
		'San Lorenzo',
		'San Martín',
		'Vera'
	),
	'AR_G' => array(
		'Aguirre',
		'Alberdi',
		'Atamisqui',
		'Avellaneda',
		'Banda',
		'Belgrano',
		'Santiago del Estero',
		'Choya',
		'Copo',
		'Figueroa',
		'General Taboada',
		'Guasayán',
		'Jiménez',
		'Juan F. Ibarra',
		'Loreto',
		'Mitre',
		'Moreno',
		'Ojo de Agua',
		'Pellegrini',
		'Quebrachos',
		'Río Hondo',
		'Rivadavia',
		'Robles',
		'Salavina',
		'San Martín',
		'Sarmiento',
		'Silípica',
	),
	'AR_V' => array(
		'Antártida Argentina',
		'Islas del Atlántico Sur',
		'Río Grande',
		'Ushuaia'
	),
	'AR_T' => array(
		'Burruyacú',
		'Tucumán',
		'Chicligasta',
		'Cruz Alta',
		'Famaillá',
		'Graneros',
		'Juan Bautista Alberdi',
		'La Cocha',
		'Leales',
		'Lules',
		'Monteros',
		'Río Chico',
		'Simoca',
		'Tafí del Valle',
		'Tafí Viejo',
		'Trancas',
		'Yerba Buena'
	)
);